name: apiverve_gdp
description: Get GDP (Gross Domestic Product) data for any country including current values and historical data going back to 1960.
version: 1.1.14
homepage: https://apiverve.com/marketplace/gdp?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/gdp-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
